@startuml

title Context Diagram
'Context diagrams (level 1): show the system in scope and its relationship with users and other systems;

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/react.puml
!include DEVICONS/nodejs.puml
!include FONTAWESOME/file_alt.puml
!include FONTAWESOME/users.puml
!include FONTAWESOME/github.puml

LAYOUT_WITH_LEGEND()

Person(user, "Users", "People looking for repository information", $sprite="users")
System(c1, "SE577 System", "Provide repository information")
SystemDb_Ext(c2, "GitHub", "Holds repository and Gist information", $sprite="github")

Rel(user, c1, "Uses", "http")
Rel_L(c2, c1, "Reads", "REST")
Rel_L(c1, c2, "Authenticate", "OAuth flow")
@enduml
