@startuml

title Container Diagram
'Container diagrams (level 2): decompose a system into interrelated containers. A container represents an application or a data store;

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/react.puml
!include DEVICONS/nodejs.puml
!include FONTAWESOME/file_alt.puml
!include FONTAWESOME/users.puml
!include FONTAWESOME/github.puml

LAYOUT_WITH_LEGEND()

Person(user, "Users", "People looking for repository information", $sprite="users")
System_Boundary(c1, "SE577 System") {
	Container(spa, "SPA", "Next.js", "The UI run in the Browser the users interact with", $sprite="react")
	Container(api, "API", "nodejs", "Provides static pages and REST endpoints", $sprite="nodejs")
	ContainerDb(db, "Database", "YAML", "Holds repository information", $sprite="file_alt")
}

Rel(user, spa, "Uses", "http")
Rel(spa, api, "Uses", "http")
Rel_L(db, api, "Reads")
@enduml
