@startuml

title Component Diagram
'Component diagrams (level 3): decompose containers into interrelated components, and relate the components to other containers or other systems;

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/react.puml
!include DEVICONS/nodejs.puml
!include FONTAWESOME/file_alt.puml
!include FONTAWESOME/users.puml
!include FONTAWESOME/github.puml
!include FONTAWESOME/html5.puml


LAYOUT_WITH_LEGEND()

Person(user, "Users", "People looking for repository information", $sprite="users")
Container_Boundary(spa, "SE577 System - HTML") {
	Component(routing, "Routing", "Next.js", "Provided by the Framework: Provides routing between views on the client", $sprite="react")
	Component(layout, "Layout", "../src/component/Layout.tsx", "Provides basic UI layout", $sprite="react")
	Component(header, "Header", "../src/component/Layout.tsx", "Provides the header UI components", $sprite="react")
	Component(footer, "Footer", "../src/component/Layout.tsx", "Provides the footer UI components", $sprite="react")
	Component(loginView, "Login page", "./login", "Provides basic UI layout", $sprite="html5")
	Component(indexView, "Index page", "./index", "Login page", $sprite="html5")
	Component(aboutView, "About page", "./about", "Simple about page", $sprite="html5")
	Component(reposView, "Repositories view", "./repos.tsx", "List of all repositories", $sprite="react")
	Component(repoComponent, "Single Repository Card", "../src/component/ACard.tsx", "Single repository UI component", $sprite="react")
	Component(repoView, "Repository view", "./repo/[repo].tsx", "Shows a single repository", $sprite="react")

}

Container_Boundary(nodejs, "SE577 System - API") {
	Component(reposController, "Repositories contrtoller", "./repos.tsx", "Repositories controller", $sprite="nodejs")
	Component(repoController, "Repository contrtoller", "./repo/[repo].tsx", "Repository controller", $sprite="nodejs")

	ContainerDb(db, "Database file", "YAML", "Holds mocked repository information", $sprite="file_alt")
}


Rel(user, routing, "Uses", "http")
Rel(routing, layout, "Uses")
Rel_R(layout, footer, "Uses")
Rel_L(layout, header, "Uses")
Rel(layout, indexView, "Uses")
Rel(layout, loginView, "Uses")
Rel(layout, aboutView, "Uses")
Rel(layout, repoView, "Uses")
Rel(layout, reposView, "Uses")
Rel_R(reposView, repoComponent, "Uses")

Lay_R(indexView, loginView)
Lay_R(loginView, aboutView)
Lay_R(aboutView, repoView)
Lay_R(repoView, reposView)


Rel_U(reposController, reposView, "Enriches", "ajax")
Rel_U(repoController, repoView, "Enriches", "ajax")
Rel_D(reposController, db, "Reads")
Rel_D(repoController, db, "Reads")

Lay_R(repoController, reposController)

Lay_D(spa, nodejs)
@enduml
