import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome!
        </h1>

        <div className={styles.grid}>
        <Link href="/about"><div className={styles.card}>
          <h2>About me</h2>
          <p>Find in-depth information about me.</p></div>
        </Link>

        <Link href="/repos"><div className={styles.card}>
          <h2>Repositories</h2>
          <p>Find a list of all the repositories</p></div>
        </Link>

        <Link href="/repos/sample"><div className={styles.card}>
          <h2>Repository example</h2>
          <p>A sample repository.</p></div>
        </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
